import { nanoid } from "nanoid";

export default [
  {
    uniqueId: nanoid(),
    id: 1,
    url: "https://media1.tenor.com/m/yO7d3c3MOTAAAAAC/%E7%86%8A%E5%87%BA%E6%B2%A1-boonie-bears.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 2,
    url: "https://media1.tenor.com/m/deGAzGlLcbYAAAAC/guang-tou-qiang-boonie-bear.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 3,
    url: "https://media1.tenor.com/m/nWUdGfY5NqoAAAAC/bear-please.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 4,
    url: "https://media1.tenor.com/m/_xZdfxSnxZkAAAAd/boonie-bears-chinese-cartoon.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 5,
    url: "https://media1.tenor.com/m/S68h903yrEwAAAAC/%E7%86%8A%E5%87%BA%E6%B2%A1-boonie-bears.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 6,
    url: "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNm5kZmszbG44MjFrZXljNzRoeGdtaHRudjQzbjlveXM5cHNkYTdtbCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/YxQkboz9DvgjcrAWQt/giphy.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 7,
    url: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExZHlob3dzYmQ1aTlwMHdoZXNoanh2cWZiYnhnemFmd204ZDcxMzdkZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/fCzYidTKzio4duEqUn/giphy.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 8,
    url: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExaWNybGZmdzZid2ZqMmJvN3dweGZmcWVqODc5NW1tMmxpaWNvbXN0bSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/stS7C4ZINZvIJycwya/giphy.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 9,
    url: "https://media1.tenor.com/m/mJQzRUjN1E0AAAAd/boonie-bears-bramble.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 10,
    url: "https://d.furaffinity.net/art/yingcartoonman/1647499348/1647499348.yingcartoonman_4d980bc5-41c1-4a06-9109-7d3bdd946c8e.gif",
    isFlipped: false,
  },
  //   {
  //     uniqueId: nanoid(),
  //     id: 11,
  //     url: "https://imgs.qiubiaoqing.com/qiubiaoqing/imgs/62068a6817aee8Xs.gif",
  //     isFlipped: false,
  //   },
  {
    uniqueId: nanoid(),
    id: 12,
    url: "https://liangcang-material.alicdn.com/prod/upload/997ff942a97243ea84db4608ece959d6.webp.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 13,
    url: "https://i.makeagif.com/media/2-29-2024/xnXTfZ.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 14,
    url: "https://s1.aigei.com/src/img/gif/31/31c0d0146f2a4e4ca1f119a6786c3cb8.gif?imageMogr2/auto-orient/thumbnail/!282x282r/gravity/Center/crop/282x282/quality/85/%7CimageView2/2/w/282&e=2051020800&token=P7S2Xpzfz11vAkASLTkfHN7Fw-oOZBecqeJaxypL:VWUJ2Tb9HamDCIZ0ho4RlXuxqWw=",
    isFlipped: false,
  },
  //   {
  //     uniqueId: nanoid(),
  //     id: 15,
  //     url: "https://imgs.qiubiaoqing.com/qiubiaoqing/imgs/6879323dbeb65y0C.gif",
  //     isFlipped: false,
  //   },
  {
    uniqueId: nanoid(),
    id: 16,
    url: "https://static.jstv.com/gather/hl_dp/20201221/99/2963665104304325587.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 17,
    url: "https://pic1.zhimg.com/v2-d07aa66a4bb9de538cbf1edc1a4a2366_1440w.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 18,
    url: "https://media.tenor.com/kVD7SxrRfBwAAAAM/%E7%86%8A%E5%87%BA%E6%B2%A1-boonie-bears.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 19,
    url: "https://media1.tenor.com/m/sPd5RVM6UWYAAAAC/%E7%86%8A%E5%87%BA%E6%B2%A1-boonie-bears.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 20,
    url: "https://media1.tenor.com/m/NUMIlucPEYMAAAAd/%E7%86%8A%E5%87%BA%E6%B2%A1-double-roar.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 21,
    url: "https://media1.tenor.com/m/vkvZ5vsSVEIAAAAC/%E7%86%8A%E5%87%BA%E6%B2%A1-boonie-bears.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 22,
    url: "https://media1.tenor.com/m/O3mZ8oexzBIAAAAC/boonie-bears-jumpscare.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 23,
    url: "https://media1.tenor.com/m/uHcLR9UorGwAAAAC/%E7%86%8A%E5%87%BA%E6%B2%A1-boonie-bears.gif",
    isFlipped: false,
  },
  {
    uniqueId: nanoid(),
    id: 24,
    url: "https://media.tenor.com/jpbpA27ayv4AAAAi/bobo-bear.gif",
    isFlipped: false,
  },
];
